from django.views.generic import TemplateView
import os
from django.conf import settings
from django.http import FileResponse, Http404

class FrontendAppView(TemplateView):
    """
    Serves the compiled React index.html.  It falls back to the static
    build folder generated by `npm run build`.  This view catches all
    routes that aren’t matched by API URLs, giving the SPA its
    client‑side routing.
    """
    def get_template_names(self):
        # Path to the built index.html
        return [os.path.join(settings.BASE_DIR, 'frontend', 'dist', 'index.html')]

    # Disable Django’s template engine for this static file
    def render_to_response(self, context, **response_kwargs):
        index_path = self.get_template_names()[0]
        if os.path.exists(index_path):
            return FileResponse(open(index_path, 'rb'), content_type='text/html')
        raise Http404("React build not found. Run `npm run build`.")
